Atelier/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls import include
from .views import mainpage_view, redirect_to_auth

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', mainpage_view, name='main'),

    path('accounts/', include('django.contrib.auth.urls')),
    path('auth/', redirect_to_auth, name='auth'),
    path('orders/', include('Order.urls')),
    path('materials/', include('Material.urls')),
    path('employees/', include('Employee.urls')),
    path('services/', include('Service.urls')),
    path('clients/', include('Client.urls'))
]

Material/urls.py
from django.urls import path
from django.conf.urls import include
from .views import all_materials, view_material, add_material, delete_material, EditMaterialView

urlpatterns = [
    path('', all_materials, name='all_materials'),

    path('view/<id>', view_material, name='view_material'),
    path('add', add_material, name='add_material'),
    path('delete/<id>', delete_material, name='delete_material'),
    path('edit/<int:pk>', EditMaterialView.as_view(), name='edit_material'),

    path('categories/', include('MaterialCategory.urls')),
]

Order/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls import include
from .views import all_orders, view_order, add_order

urlpatterns = [
    path('', all_orders, name='all_orders'),
    path('view/<id>', view_order, name='view_order'),
    path('add/', add_order, name='add_order'),
]

Material/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from MaterialCategory.models import MaterialCategory

class Material(models.Model):
    name = models.CharField(db_column='Name',
                            verbose_name=_('Name'),
                            max_length=50)
    vendor_code = models.CharField(db_column='Vendor code',
                                   verbose_name=_('Vendor code'),
                                   max_length=45,
                                   blank=True,
                                   null=True)
    id_category = models.ForeignKey(MaterialCategory,
                                    models.SET_NULL,
                                    db_column='id_Category',
                                    verbose_name=_('Category'),
                                    blank=True,
                                    null=True)
    comment = models.TextField(db_column='Comment',
                               verbose_name=_('Comment'),
                               blank=True,
                               null=True)
    balance = models.IntegerField(db_column='Balance',
                                  verbose_name=_('Balance (meters or pieces)'),
                                  blank=True,
                                  null=True)
    color = models.CharField(db_column='Color',
                             verbose_name=_('Color'),
                             max_length=255,
                             blank=True,
                             null=True)

    class Meta:
        managed = False
        db_table = 'material'
        verbose_name = _('Material')
        verbose_name_plural = _('Materials')

    def __str__(self):
        return _('%s %s (balance: %s m)') % (self.name, self.color, self.balance)

    def get_absolute_url(self):
        return f'/materials/view/{self.id}'

ServicePrice/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
# from django.db.models.signals import post_save
# from django.dispatch import receiver
from Service.models import Service

class ServicePrice(models.Model):
    id_service = models.ForeignKey(Service,
                                   models.CASCADE,
                                   db_column='id_Service',
                                   verbose_name=_('Service'),
                                   blank=True,
                                   null=True)
    price = models.DecimalField(db_column='Price',
                                verbose_name=_('Price'),
                                max_digits=19,
                                decimal_places=2,
                                blank=True,
                                null=True)
    modification_date = models.DateTimeField(db_column='Modification date',
                                             verbose_name=_('Modification date'),
                                             blank=True,
                                             null=True)

    class Meta:
        managed = False
        db_table = 'service price'
        verbose_name = _('Service price')
        verbose_name_plural = _('Services prices')


    def __str__(self):
        return f"{self.id_service.name}, {self.modification_date}, {self.price}"

Material/forms.py
from django import forms
from django.forms import ModelForm, TextInput, NumberInput, Textarea, Select
from django.utils.translation import ugettext_lazy as _
from MaterialCategory.models import MaterialCategory
from MaterialPrice.models import MaterialPrice
from .models import Material

class MaterialForm(ModelForm):
    id_category = forms.ModelChoiceField(queryset=MaterialCategory.objects.all(),
                                         widget=Select(attrs={
                                             'class': 'custom-select',
                                         }))

    class Meta:
        model = Material
        fields = '__all__'

        widgets = {
            'name': TextInput(attrs={
                'class': 'form-control',
            }),
            'vendor_code': TextInput(attrs={
                'class': 'form-control',
            }),
            'comment': Textarea(attrs={
                'class': 'form-control',
                'rows': 3
            }),
            'balance': NumberInput(attrs={
                'class': 'form-control',
            }),
            'color': TextInput(attrs={
                'class': 'form-control',
            }),
        }

class MaterialPriceForm(ModelForm):
    class Meta:
        model = MaterialPrice
        fields = ['id_material', 'price']
        widgets = {
            'price': NumberInput(attrs={
                'class': 'form-control',
            }),
        }

Material/views.py
from django.http import Http404
from datetime import datetime
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.views.generic import UpdateView
from django.utils.translation import ugettext_lazy as _
from MaterialPrice.views import get_current_price, get_price_history
from MaterialCategory.models import MaterialCategory
from MaterialPrice.models import MaterialPrice
from .models import Material
from .forms import MaterialForm, MaterialPriceForm

@login_required(login_url='auth')
def all_materials(request):
    context = {}
    context['user_group'] = request.user.groups.all()[0].name
    material_list = []
    materials = Material.objects.all()
    for material in materials:
        material_list.append(
            {
                'material': material,
                'material_price': get_current_price(material.id)
            }
        )
    context['materials'] = material_list
    return render(request, 'material/all_materials.html', context)

@login_required(login_url='auth')
def view_material(request, id):
    context = {}
    context['user_group'] = request.user.groups.all()[0].name

    material = Material.objects.get(id=id)
    context['material'] = material

    context['material_prices'] = get_price_history(material.id)
    context['material_price'] = get_current_price(material.id)
    return render(request, 'material/view_material.html', context)

@login_required(login_url='auth')
def add_material(request):
    context = {}
    context['user_group'] = request.user.groups.all()[0].name

    error = ''
    if request.method == 'POST':
        material_form = MaterialForm(request.POST)
        material_price_form = MaterialPriceForm(request.POST)
        if material_form.is_valid() and material_price_form.is_valid():
            material = material_form.save()
            
            material_price = material_price_form.save(commit=False)
            material_price.id_material = Material.objects.get(id=material.pk)
            material_price.modification_date = datetime.now()
            material_price.save()

            return redirect('all_materials')
        else:
            error = _('Form is invalid')

    material_form = MaterialForm()
    material_price_form = MaterialPriceForm()
    context['form'] = material_form
    context['material_price_form'] = material_price_form
    context['error'] = error

    return render(request, 'material/add_material.html', context)

@login_required(login_url='auth')
def delete_material(request, id):
    context = {}
    context['user_group'] = request.user.groups.all()[0].name

    Material.objects.filter(id=id).delete()
    return redirect('all_materials')

class EditMaterialView(UpdateView):
    model = Material
    template_name = 'material/add_material.html'
    form_class = MaterialForm
    second_form_class = MaterialPriceForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user_group'] = self.request.user.groups.all()[0].name

        if 'material_price_form' not in context:
            current_price = MaterialPrice.objects.filter(id_material=self.kwargs['pk']).order_by('-modification_date')[0]

            context['material_price_form'] = MaterialPriceForm(instance=current_price)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = super(EditMaterialView, self).get_context_data(**kwargs)

        if 'form' in context:
            form = MaterialForm(request.POST, instance=self.object)
            if form.is_valid():
                form.save()
            else:
                context['form'] = form

        current_price = MaterialPrice.objects.filter(id_material=self.object.id).order_by('-modification_date')[0]
        if 'price' in request.POST:
            if request.POST['price'] != '':
                new_price = float(request.POST['price'])
            else:
                new_price = float(0)
            if new_price != current_price.price:
                new_material_price = MaterialPrice(id_material=self.object, price=new_price, modification_date=datetime.now())
                new_material_price.save()
        
        return redirect(self.object.get_absolute_url())

templates/material/add_material.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans "New material" %}{% endblock %}

{% block content %}
<a class="btn btn-link" href="{{request.META.HTTP_REFERER}}">← {% trans 'Previous page' %}</a>

<h1>{% trans "New material" %}</h1>

{% if error %}
    <div class="alert alert-danger" role="alert">{{ error }}</div>
{% endif %}
<form class="mt-4" method="POST">
    {% csrf_token %}
    <h4>{% trans "Material's information" %}</h4>
    <div class="form-row mb-2 mt-2">
        <div class="col-md-4 mb-3">
            <label for="id_name">{% trans "Name" %}</label>
            {{ form.name }}
        </div>
        <div class="col-md-4 mb-3">
            <label for="id_vendor_code">{% trans "Vendor code" %}</label>
            {{ form.vendor_code }}
        </div>
        <div class="col-md-4 mb-3">
            <label for="id_color">{% trans "Color" %}</label>
            {{ form.color }}
        </div>
    </div>
    <div class="form-row mb-2">
        
        <div class="col-md-4 mb-3">
            <label for="id_id_category">{% trans "Category" %}</label>
            {{ form.id_category }}
        </div>
        <div class="col-md-4 mb-3">
            <label for="id_balance">{% trans "Balance (meters or pieces)" %}</label>
            {{ form.balance }}
        </div>
        <div class="col-md-4 mb-3">
            <label for="id_price">{% trans "Price" %}</label>
            {{ material_price_form.price }}
        </div>

    </div>
    <div class="form-row mb-3">
        <div class="col-md-12 mb-3">
            <label for="id_comment">{% trans "Comment" %}</label>
            {{ form.comment }}
        </div>
    </div>
    
    <button class="btn btn-success" type="submit">{% trans "Save" %}</button>
</form>

{% endblock %}

templates/material/all_categories.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans "Materials categories" %}{% endblock %}

{% block content %}

<h1>{% trans "Materials categories" %}</h1>
<div class="table-responsive mt-3">
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">{% trans "Name" %}</th>
                <th scope="col">{% trans "Quantity" %}</th>
            </tr>
        </thead>
        <tbody>
            {% for category in categories %}
                <tr>
                    <th scope="row">
                        <a href="{% url 'view_category' id=category.id %}">{{ category.name }}</a>
                    </th>
                    <td>{{ category.materials_count }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

templates/material/all_materials.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans "Materials" %}{% endblock %}

{% block content %}

<h1>{% trans "Materials" %}</h1>

{% if user_group == 'Managers' %}
    <a href="{% url 'add_material' %}" class="btn btn-primary">{% trans "New material" %}</a>
{% endif %}

<div class="table-responsive mt-3">
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">{% trans "Name" %}</th>
                <th scope="col">{% trans "Category" %}</th>
                <th scope="col">{% trans "Color" %}</th>
                <th scope="col">{% trans "Vendor code" %}</th>
                <th scope="col">{% trans "Balance (meters or pieces)" %}</th>
                <th scope="col">{% trans "Price" %}</th>
            </tr>
        </thead>
        <tbody>
            {% for item in materials %}
                <tr>
                    <th scope="row">
                        <a href="{% url 'view_material' id=item.material.id %}">{{ item.material.name }}</a>
                    </th>
                    <td>
                        {% if item.material.id_category %}
                            <a href="{% url 'view_category' id=item.material.id_category.id %}">{{ item.material.id_category }}</a>
                        {% else %}
                            <i>{% trans "Undefinedd" %}</i>
                        {% endif %}
                    </td>
                    <td>{{ item.material.color }}</td>
                    <td>{{ item.material.vendor_code }}</td>
                    <td>{{ item.material.balance }}</td>
                    <td>{{ item.material_price }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

templates/material/view_material.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{{ material.name }}, {{ material.color }}{% endblock %}

{% block content %}
<a class="btn btn-link" href="{{request.META.HTTP_REFERER}}">← {% trans 'Previous page' %}</a>

<h1>{{ material.name }}, {{ material.color }}</h1>

{% if user_group == 'Managers' %}
    <a href="{% url 'edit_material' pk=material.id %}" class="btn btn-info">{% trans "Edit" %}</a>
{% endif %}

<div class="table-responsive mt-3">
    <table class="table">
        <tbody>
            <tr>
                <th scope="row">{% trans "Name" %}</th>
                <td>{{ material.name }}</td>
            </tr>
            <tr>
                <th scope="row">{% trans "Category" %}</th>
                <td>
                    {% if material.id_category %}
                        <a href="{% url 'view_category' id=material.id_category.id %}">{{ material.id_category }}</a>
                    {% else %}
                        <i>{% trans "Undefinedd" %}</i>
                    {% endif %}
                </td>
            </tr>
            <tr>
                <th scope="row">{% trans "Color" %}</th>
                <td>{{ material.color }}</td>
            </tr>
            <tr>
                <th scope="row">{% trans "Vendor code" %}</th>
                <td>{{ material.vendor_code }}</td>
            </tr>
            <tr>   
                <th scope="row">{% trans "Balance (meters or pieces)" %}</th>
                <td>{{ material.balance }}</td>
            </tr>
            <tr>
                <th scope="row">{% trans "Price" %}</th>
                <td>{{ material_price }}</td>
            </tr>
            {% if material.comment %}
                <tr>
                    <th scope="row">{% trans "Comment" %}</th>
                    <td>{{ material.comment }}</td>
                </tr>
            {% endif %}
        </tbody>
    </table>
</div>

<h4>{% trans "Price change" %}</h4>
<div class="table-responsive mt-3">
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">{% trans "Modification date" %}</th>
                <th scope="col">{% trans "New price" %}</th>
            </tr>
        </thead>
        <tbody>
            {% if material_prices %}
                {% for price in material_prices %}
                    <tr>
                        <td>{{ price.modification_date }}</td>
                        <td>{{ price.price }}</td>
                    </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td colspan="2" class="text-center font-italic">{% trans "There are not any price changes" %}</td>
                </tr> 
            {% endif %}
        </tbody>
    </table>
</div>


{% if user_group == 'Managers' %}
<!-- Button trigger modal -->
    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteConfirmationModal">
        {% trans "Delete" %} {% trans "material" %}
    </button>

    <!-- Delete Confirmation Modal -->
    <div class="modal fade" id="deleteConfirmationModal" tabindex="-1" role="dialog" aria-labelledby="deleteConfirmationModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteConfirmationModalLabel">{% trans "Confirmation required" %}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    {% trans "Are you sure that you want to delete" %} {% trans "material" %} - {{ material.name }}, {{ material.color }}?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-success" data-dismiss="modal">{% trans "Cancel" %}</button>
                    <a href="{% url 'delete_material' id=material.id %}" class="btn btn-danger">
                        {% trans "Delete" %} {% trans "material" %}
                    </a>
                </div>
            </div>
        </div>
    </div>
{% endif %}

{% endblock %}