Atelier/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls import include
from .views import mainpage_view, redirect_to_auth

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', mainpage_view, name='main'),

    path('accounts/', include('django.contrib.auth.urls')),
    path('auth/', redirect_to_auth, name='auth'),
    path('orders/', include('Order.urls')),
    path('materials/', include('Material.urls')),
    path('employees/', include('Employee.urls')),
    path('services/', include('Service.urls')),
    path('clients/', include('Client.urls'))
]

Client/urls.py
from django.urls import path
from django.conf.urls import include
from .views import all_clients, view_client, add_client, delete_client, EditClientView

urlpatterns = [
    path('', all_clients, name='all_clients'),
    path('view/<id>', view_client, name='view_client'),
    path('add', add_client, name='add_client'),
    path('delete/<id>', delete_client, name='delete_client'),
    path('edit/<int:pk>', EditClientView.as_view(), name='edit_client'),
]

Order/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls import include
from .views import all_orders, view_order, add_order

urlpatterns = [
    path('', all_orders, name='all_orders'),
    path('view/<id>', view_order, name='view_order'),
    path('add/', add_order, name='add_order'),
]

Client/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

class Client(models.Model):
    first_name = models.CharField(db_column='First name',
                                  verbose_name=_('First name'),
                                  max_length=50)
    last_name = models.CharField(db_column='Last name',
                                 verbose_name=_('Last name'),
                                 max_length=255)
    phone = models.CharField(db_column='Phone',
                             verbose_name=_('Phone'),
                             max_length=255)
    height = models.IntegerField(db_column='Height',
                                 verbose_name=_('Height'),
                                 blank=True,
                                 null=True)
    chest_girth = models.IntegerField(db_column='Chest girth',
                                      verbose_name=_('Chest girth'),
                                      blank=True,
                                      null=True)
    chest_height = models.IntegerField(db_column='Chest height',
                                       verbose_name=_('Chest height'),
                                       blank=True,
                                       null=True)
    waist_girth = models.IntegerField(db_column='Waist girth',
                                      verbose_name=_('Waist girth'),
                                      blank=True,
                                      null=True)
    hip_girth = models.IntegerField(db_column='Hip girth',
                                    verbose_name=_('Hip girth'),
                                    blank=True,
                                    null=True)
    neck_girth = models.IntegerField(db_column='Neck girth',
                                     verbose_name=_('Neck girth'),
                                     blank=True,
                                     null=True)
    shoulder_girth = models.IntegerField(db_column='Shoulder girth',
                                         verbose_name=_('Shoulder girth'),
                                         blank=True,
                                         null=True)
    hand_girth = models.IntegerField(db_column='Hand girth',
                                     verbose_name=_('Hand girth'),
                                     blank=True,
                                     null=True)
    hand_length = models.IntegerField(db_column='Hand length',
                                      verbose_name=_('Hand length'),
                                      blank=True,
                                      null=True)
    back_width = models.IntegerField(db_column='Back width',
                                     verbose_name=_('Back width'),
                                     blank=True,
                                     null=True)
    length_waist_floor = models.IntegerField(db_column='Length waist-floor',
                                             verbose_name=_('Length waist-floor'),
                                             blank=True,
                                             null=True)

    class Meta:
        managed = False
        db_table = 'client'
        verbose_name = _('Client')
        verbose_name_plural = _('Clients')

    def __str__(self):
        return '{0} {1}'.format(self.last_name, self.first_name)

    def get_absolute_url(self):
        return f'/clients/view/{self.id}'

Client/forms.py
from django import forms
from django.forms import ModelForm, TextInput, NumberInput
from django.utils.translation import ugettext_lazy as _
from .models import Client

class ClientForm(ModelForm):
    class Meta:
        model = Client
        fields = '__all__'

        widgets = {
            'first_name': TextInput(attrs={
                'class': 'form-control',
                'placeholder': _('Ivan')
            }),
            'last_name': TextInput(attrs={
                'class': 'form-control',
                'placeholder': _('Ivanov'),
            }),
            'phone': TextInput(attrs={
                'class': 'form-control',
                'type': 'tel',
                'pattern': '7[0-9]{10}',
                'placeholder': '79001234567',
            }),
            'height': NumberInput(attrs={
                'class': 'form-control',
            }),
            'chest_girth': NumberInput(attrs={
                'class': 'form-control',
            }),
            'chest_height': NumberInput(attrs={
                'class': 'form-control',
            }),
            'waist_girth': NumberInput(attrs={
                'class': 'form-control',
            }),
            'hip_girth': NumberInput(attrs={
                'class': 'form-control',
            }),
            'neck_girth': NumberInput(attrs={
                'class': 'form-control',
            }),
            'shoulder_girth': NumberInput(attrs={
                'class': 'form-control',
            }),
            'hand_girth': NumberInput(attrs={
                'class': 'form-control',
            }),
            'hand_length': NumberInput(attrs={
                'class': 'form-control',
            }),
            'back_width': NumberInput(attrs={
                'class': 'form-control',
            }),
            'length_waist_floor': NumberInput(attrs={
                'class': 'form-control',
            }),
        }

Client/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.views.generic import UpdateView
from django.utils.translation import ugettext_lazy as _
from Order.views import get_client_orders
from .forms import ClientForm
from .models import Client

@login_required(login_url='auth')
def all_clients(request):
    context = {}
    context['user_group'] = request.user.groups.all()[0].name

    context['clients'] = Client.objects.all()
    return render(request, 'client/all_clients.html', context)

@login_required(login_url='auth')
def view_client(request, id):
    context = {}
    context['user_group'] = request.user.groups.all()[0].name

    client_object = Client.objects.get(id=id)
    context['client'] = {
        'client_object': client_object
    }
    context['orders'] = get_client_orders(id)
    return render(request, 'client/view_client.html', context)
    
@login_required(login_url='auth')
def add_client(request):
    context = {}
    context['user_group'] = request.user.groups.all()[0].name

    error = ''
    if request.method == 'POST':
        form = ClientForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('all_clients')
        else:
            error = _('Form is invalid')

    form = ClientForm()
    context['form'] = form
    context['error'] = error

    return render(request, 'client/add_client.html', context)

@login_required(login_url='auth')
def delete_client(request, id):
    context = {}
    context['user_group'] = request.user.groups.all()[0].name

    Client.objects.filter(id=id).delete()
    return redirect('all_clients')

class EditClientView(UpdateView):
    model = Client
    template_name = 'client/add_client.html'
    form_class = ClientForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user_group'] = self.request.user.groups.all()[0].name
        return context

templates/client/add_client.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans "New client" %}{% endblock %}

{% block content %}
<a class="btn btn-link" href="{{request.META.HTTP_REFERER}}">← {% trans 'Previous page' %}</a>

<h1>{% trans "New client" %}</h1>

{% if error %}
    <div class="alert alert-danger" role="alert">{{ error }}</div>
{% endif %}
<form class="mt-4" method="POST">
    {% csrf_token %}
    <h4>{% trans "Contact details" %}</h4>
    <div class="form-row mb-3">
        <div class="col-md-4 mb-3">
            <label for="id_first_name">{% trans "First name" %}</label>
            {{ form.first_name }}
        </div>
        <div class="col-md-4 mb-3">
            <label for="id_last_name">{% trans "Last name" %}</label>
            {{ form.last_name }}
        </div>
      <div class="col-md-4 mb-3">
        <label for="id_phone">{% trans "Phone" %}</label>
        <div class="input-group">
            <div class="input-group-prepend">
                <span class="input-group-text" id="inputGroupPrepend2">+</span>
            </div>
            {{ form.phone }}
        </div>
      </div>
    </div>
    <h4>{% trans "Body" %}</h4>
    <div class="form-row mb-3">
        <div class="col-md-2 mb-3">
            <label for="id_height">{% trans "Height" %}</label>
            {{ form.height }}
        </div>
        <div class="col-md-2 mb-3">
            <label for="id_chest_girth">{% trans "Chest girth" %}</label>
            {{ form.chest_girth }}
        </div>
        <div class="col-md-2 mb-3">
            <label for="id_chest_height">{% trans "Chest height" %}</label>
            {{ form.chest_height }}
        </div>
        <div class="col-md-2 mb-3">
            <label for="id_waist_girth">{% trans "Waist girth" %}</label>
            {{ form.waist_girth }}
        </div>
        <div class="col-md-2 mb-3">
            <label for="id_neck_girth">{% trans "Neck girth" %}</label>
            {{ form.neck_girth }}
        </div>
        <div class="col-md-2 mb-3">
            <label for="id_back_width">{% trans "Back width" %}</label>
            {{ form.back_width }}
        </div>
    </div>
    <h4>{% trans "Hands" %}</h4>
    <div class="form-row mb-3">
        <div class="col-md-3 mb-3">
            <label for="id_shoulder_girth">{% trans "Shoulder girth" %}</label>
            {{ form.shoulder_girth }}
        </div>
        <div class="col-md-3 mb-3">
            <label for="id_hand_girth">{% trans "Hand girth" %}</label>
            {{ form.hand_girth }}
        </div>
        <div class="col-md-3 mb-3">
            <label for="id_hand_length">{% trans "Hand length" %}</label>
            {{ form.hand_length }}
        </div>
    </div>
    <h4>{% trans "Feet" %}</h4>
    <div class="form-row mb-3">
        <div class="col-md-3 mb-3">
            <label for="id_hip_girth">{% trans "Hip girth" %}</label>
            {{ form.hip_girth }}
        </div>
        <div class="col-md-3 mb-3">
            <label for="id_length_waist_floor">{% trans "Length waist-floor" %}</label>
            {{ form.length_waist_floor }}
        </div>
    </div>
    <button class="btn btn-success" type="submit">{% trans "Save" %}</button>
</form>

{% endblock %}

templates/client/all_clients.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans "Clients" %}{% endblock %}

{% block content %}

<h1>{% trans "Clients" %}</h1>
<a href="{% url 'add_client' %}" class="btn btn-primary">{% trans "New client" %}</a>
<div class="table-responsive mt-3">
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">{% trans "Last name" %}</th>
                <th scope="col">{% trans "First name" %}</th>
                <th scope="col">{% trans "Phone" %}</th>
            </tr>
        </thead>
        <tbody>
            {% for client in clients %}
                <tr>
                    <th scope="row">
                        <a href="{% url 'view_client' id=client.id %}">{{ client.last_name }}</a>
                    </th>
                    <td>
                        <a href="{% url 'view_client' id=client.id %}">{{ client.first_name }}</a>
                    </td>
                    <td>{{ client.phone }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

templates/client/view_client.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
    {{ client.client_object }}
{% endblock %}

{% block content %}
<a class="btn btn-link" href="{{request.META.HTTP_REFERER}}">← {% trans 'Previous page' %}</a>

<h1>{{ client.client_object }}</h1>

<a href="{% url 'edit_client' pk=client.client_object.id %}" class="btn btn-info">{% trans "Edit" %}</a>

<div class="table-responsive mt-3">
    <table class="table">
        <tbody>
            <tr>
                <th scope="row">{% trans "Last name" %}</th>
                <td>
                    {{ client.client_object.last_name }}
                </td>
            </tr>
            <tr>
                <th scope="row">{% trans "First name" %}</th>
                <td>
                    {{ client.client_object.first_name }}
                </td>
            </tr>
            <tr>
                <th scope="row">{% trans "Phone" %}</th>
                <td>{{ client.client_object.phone }}</td>
            </tr>
            {% if client.client_object.height %}
                <tr>
                    <th scope="row">{% trans "Height" %}</th>
                    <td>{{ client.client_object.height }}</td>
                </tr>
            {% endif %}
            {% if client.client_object.chest_girth %}
                <tr>
                    <th scope="row">{% trans "Chest girth" %}</th>
                    <td>{{ client.client_object.chest_girth }}</td>
                </tr>
            {% endif %}
            {% if client.client_object.chest_height %}
                <tr>
                    <th scope="row">{% trans "Chest height" %}</th>
                    <td>{{ client.client_object.chest_height }}</td>
                </tr>
            {% endif %}
            {% if client.client_object.waist_girth %}
                <tr>
                    <th scope="row">{% trans "Waist girth" %}</th>
                    <td>{{ client.client_object.waist_girth }}</td>
                </tr>
            {% endif %}
            {% if client.client_object.hip_girth %}
                <tr>
                    <th scope="row">{% trans "Hip girth" %}</th>
                    <td>{{ client.client_object.hip_girth }}</td>
                </tr>
            {% endif %}
            {% if client.client_object.neck_girth %}
                <tr>
                    <th scope="row">{% trans "Neck girth" %}</th>
                    <td>{{ client.client_object.neck_girth }}</td>
                </tr>
            {% endif %}
            {% if client.client_object.shoulder_girth %}
                <tr>
                    <th scope="row">{% trans "Shoulder girth" %}</th>
                    <td>{{ client.client_object.shoulder_girth }}</td>
                </tr>
            {% endif %}
            {% if client.client_object.hand_girth %}
                <tr>
                    <th scope="row">{% trans "Hand girth" %}</th>
                    <td>{{ client.client_object.hand_girth }}</td>
                </tr>
            {% endif %}
            {% if client.client_object.hand_length %}
                <tr>
                    <th scope="row">{% trans "Hand length" %}</th>
                    <td>{{ client.client_object.hand_length }}</td>
                </tr>
            {% endif %}
            {% if client.client_object.back_width %}
                <tr>
                    <th scope="row">{% trans "Back width" %}</th>
                    <td>{{ client.client_object.back_width }}</td>
                </tr>
            {% endif %}
            {% if client.client_object.length_waist_floor %}
                <tr>
                    <th scope="row">{% trans "Length waist-floor" %}</th>
                    <td>{{ client.client_object.length_waist_floor }}</td>
                </tr>
            {% endif %}
        </tbody>
    </table>
</div>

<h4>{% trans "Orders" %}</h4>
<div class="table-responsive mt-3">
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">{% trans "#" %}</th>
                <th scope="col">{% trans "Status" %}</th>
                <th scope="col">{% trans "Service" %}</th>
                <th scope="col">{% trans "Start date" %}</th>
                <th scope="col">{% trans "Cost" %}</th>
            </tr>
        </thead>
        <tbody>
            {% if orders %}
                {% for order in orders %}
                    <tr>
                        <td>
                            <a href="{% url 'view_order' id=order.order_object.id %}">{{ order.order_object.id }}</a>
                        </td>
                        <td>{{ order.localized_status }}</td>
                        <td>
                            {% if order.order_object.id_service %}
                                <a href="{% url 'view_service' id=order.order_object.id_service.id %}">{{ order.order_object.id_service }}</a>
                            {% else %}
                                <i>{% trans "Undefinedd" %}</i>
                            {% endif %}
                        </td>
                        <td>{{ order.order_object.start_date }}</td>
                        <td>{{ order.order_object.cost }}</td>
                    </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td colspan="5" class="text-center font-italic">{% trans "The client has not made any order" %}</td>
                </tr> 
            {% endif %}
        </tbody>
    </table>
</div>

<!-- Button trigger modal -->
<button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteConfirmationModal">
    {% trans "Delete client" %}
</button>
  
<!-- Modal -->
<div class="modal fade" id="deleteConfirmationModal" tabindex="-1" role="dialog" aria-labelledby="deleteConfirmationModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteConfirmationModalLabel">{% trans "Confirmation required" %}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                {% trans "Are you sure that you want to delete client" %} - {{ client.client_object }}?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-success" data-dismiss="modal">{% trans "Cancel" %}</button>
                <a href="{% url 'delete_client' id=client.client_object.id %}" class="btn btn-danger">{% trans "Delete client" %}</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}