Atelier/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls import include
from .views import mainpage_view, redirect_to_auth

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', mainpage_view, name='main'),

    path('accounts/', include('django.contrib.auth.urls')),
    path('auth/', redirect_to_auth, name='auth'),
    path('orders/', include('Order.urls')),
    path('materials/', include('Material.urls')),
    path('employees/', include('Employee.urls')),
    path('services/', include('Service.urls')),
    path('clients/', include('Client.urls'))
]

Order/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls import include
from .views import all_orders, view_order, add_order

urlpatterns = [
    path('', all_orders, name='all_orders'),
    path('view/<id>', view_order, name='view_order'),
    path('add/', add_order, name='add_order'),
]

Order/models.py
from django.db import models
from django.contrib import admin
from django.utils.translation import ugettext_lazy as _
# from django.db.models.signals import post_save
# from django.dispatch import receiver
from Client.models import Client
from Employee.models import Employee
from Material.models import Material
from Service.models import Service

class Order(models.Model):
    class OrderStatus(models.TextChoices):
        CREATED = 'Created', _('Created')
        CANCELLED = 'Cancelled', _('Cancelled')
        IN_PROGRESS = 'In progress', _('In progress')
        COMPLETED = 'Completed', _('Completed')
        FITTING_REQUIRED = 'Fitting required', _('Fitting required')
        RETURNED_FOR_REWORK = 'Returned for rework', _('Returned for rework')

    class Urgency(models.TextChoices):
        LOW = 'Low', _('Low urgency')
        MEDIUM = 'Medium', _('Medium urgency')
        HIGH = 'High', _('High urgency')
        VERY_HIGH = 'Very high', _('Very high urgency')

    class LabourIntensity(models.TextChoices):
        LOW = 'Low', _('1-3 days')
        MEDIUM = 'Medium', _('4-6 days')
        HIGH = 'High', _('7-9 days')
        VERY_HIGH = 'Very high', _('10+ days')

    class PaymentStatus(models.TextChoices):
        PENDING = 'Pending payment', _('Pending payment')
        PREPAYMENT_MADE = 'Prepayment made', _('Prepayment made')
        PAID = 'Paid', _('Paid')

    id_service = models.ForeignKey(Service,
                                   models.SET_NULL,
                                   db_column='id_Service',
                                   verbose_name=_('Service'),
                                   blank=True,
                                   null=True)
    status = models.CharField(db_column='Status',
                              verbose_name=_('Status'),
                              max_length=20,
                              choices=OrderStatus.choices,
                              default=OrderStatus.CREATED)
    payment_status = models.CharField(db_column='Payment status',
                                      verbose_name=_('Payment status'),
                                      max_length=15,
                                      choices=PaymentStatus.choices,
                                      blank=True,
                                      null=True)
    prepayment = models.DecimalField(db_column='Prepayment',
                                     verbose_name=_('Prepayment'),
                                     max_digits=19,
                                     decimal_places=2,
                                     blank=True,
                                     null=True)
    cost = models.DecimalField(db_column='Cost',
                               verbose_name=_('Cost'),
                               max_digits=19,
                               decimal_places=2,
                               blank=True,
                               null=True)
    start_date = models.DateTimeField(db_column='Start date',
                                      verbose_name=_('Start date'),
                                      blank=True,
                                      null=True)
    target_completion_date = models.DateTimeField(db_column='Target completion date', 
                                                  verbose_name=_('Target completion date'),
                                                  blank=True, 
                                                  null=True)
    end_date = models.DateTimeField(db_column='End date',
                                    verbose_name=_('End date'),
                                    blank=True,
                                    null=True)
    id_client = models.ForeignKey(Client,
                                  models.SET_NULL,
                                  db_column='id_Client',
                                  verbose_name=_('Client'),
                                  blank=True,
                                  null=True)
    id_employee = models.ForeignKey(Employee,
                                    models.SET_NULL,
                                    db_column='id_Employee',
                                    verbose_name=_('Employee'),
                                    blank=True,
                                    null=True)
    labour_intensity = models.CharField(db_column='Labour intensity',
                                        verbose_name=_('Labour intensity'),
                                        max_length=9,
                                        choices=LabourIntensity.choices,
                                        default=LabourIntensity.LOW)
    urgency = models.CharField(db_column='Urgency',
                               verbose_name=_('Urgency'),
                               max_length=9,
                               choices=Urgency.choices,
                               default=Urgency.LOW)
    materials = models.ManyToManyField(Material, through='OrderMaterials', blank=True, null=True)
    comment = models.TextField(db_column='Comment',
                               verbose_name=_('Commentt'),
                               blank=True,
                               null=True)

    class Meta:
        managed = False
        db_table = 'order'
        verbose_name = _('Order')
        verbose_name_plural = _('Orders')

    def __str__(self):
        return _('%s, Order #%s, created on: %s, sum: %s') % (get_localized_status(self.status), self.id, self.start_date, self.cost)

def get_localized_status(status):
    order_statuses = {
        'Created': _('Created'),
        'Cancelled': _('Cancelled'),
        'In progress': _('In progress'),
        'Fitting required': _('Fitting required'),
        'Completed': _('Completed'),
        'Returned for rework': _('Returned for rework')
    }
    return order_statuses[status]

class OrderMaterials(models.Model):
    id_order = models.ForeignKey(Order,
                                 models.CASCADE,
                                 db_column='id_Order',
                                 verbose_name=_('Order'),
                                 blank=True,
                                 null=True)
    id_material = models.ForeignKey(Material,
                                    models.CASCADE,
                                    db_column='id_Material',
                                    verbose_name=_('Material'),
                                    blank=True,
                                    null=True)
    material_quantity = models.IntegerField(db_column='Material quantity',
                                            verbose_name=_('Material quantity'),
                                            blank=True,
                                            null=True)

    class Meta:
        managed = False
        db_table = 'order materials'
        verbose_name = _('Order material')
        verbose_name_plural = _('Order materials')

# @receiver(post_save, sender=Order)
# def update_material_quantity(sender, instance, **kwargs):
#     order_id = instance.id
#     order_materials = OrderMaterials.objects.filter(id_order=order_id)
#     for item in order_materials:
#         material = Material.objects.get(id=item.id_material.id)
#         material.balance -= item.material_quantity
#         material.save()
#         print(material)

class OrderMaterialsInline(admin.TabularInline):
    model = OrderMaterials
    extra = 1

class OrderAdmin(admin.ModelAdmin):
    inlines = (OrderMaterialsInline,)

Material/forms.py
from django import forms
from django.forms import ModelForm, TextInput, NumberInput, Textarea, Select
from django.utils.translation import ugettext_lazy as _
from MaterialCategory.models import MaterialCategory
from MaterialPrice.models import MaterialPrice
from .models import Material

class MaterialForm(ModelForm):
    id_category = forms.ModelChoiceField(queryset=MaterialCategory.objects.all(),
                                         widget=Select(attrs={
                                             'class': 'custom-select',
                                         }))

    class Meta:
        model = Material
        fields = '__all__'

        widgets = {
            'name': TextInput(attrs={
                'class': 'form-control',
            }),
            'vendor_code': TextInput(attrs={
                'class': 'form-control',
            }),
            'comment': Textarea(attrs={
                'class': 'form-control',
                'rows': 3
            }),
            'balance': NumberInput(attrs={
                'class': 'form-control',
            }),
            'color': TextInput(attrs={
                'class': 'form-control',
            }),
        }

class MaterialPriceForm(ModelForm):
    class Meta:
        model = MaterialPrice
        fields = ['id_material', 'price']
        widgets = {
            'price': NumberInput(attrs={
                'class': 'form-control',
            }),
        }

Order/views.py
from django.shortcuts import render, redirect
from datetime import datetime
from django.contrib.auth.decorators import login_required
from django.utils.translation import ugettext_lazy as _
from django.db import models

from .models import Order, OrderMaterials
from .forms import OrderForm

from Material.models import Material
from MaterialPrice.views import get_current_price
from Fitting.views import get_fittings

def all_orders(request):
    context = {}
    context['user_group'] = request.user.groups.all()[0].name

    context['orders'] = get_orders()

    return render(request, 'order/all_orders.html', context)

def view_order(request, id):
    context = {}
    context['user_group'] = request.user.groups.all()[0].name

    order = Order.objects.get(id=id)

    order_materials_object = get_order_materials(id)

    context['order'] = {
        'order_object': order,
        'localized_status': get_localized_status(order.status),
        'localized_payment_status': get_localized_payment_status(order.payment_status),
        'localized_urgency': get_localized_urgency(order.urgency),
        'localized_labour_intensity': get_localized_labour_intensity(order.labour_intensity),
        'materials': get_order_materials(order.id),
        'fittings': get_fittings(order)
    }

    return render(request, 'order/view_order.html', context)

def get_orders():
    orders = Order.objects.all()
    orders_list = []
    for order in orders:
        orders_list.append({
            'order_object': order,
            'localized_status': get_localized_status(order.status),
            'localized_payment_status': get_localized_payment_status(order.payment_status),
            'localized_urgency': get_localized_urgency(order.urgency),
            'localized_labour_intensity': get_localized_labour_intensity(order.labour_intensity),
        })
    return orders_list

def get_client_orders(id):
    orders = Order.objects.filter(id_client=id)
    orders_list = []
    for order in orders:
        orders_list.append({
            'order_object': order,
            'localized_status': get_localized_status(order.status),
            'localized_payment_status': get_localized_payment_status(order.payment_status),
            'localized_urgency': get_localized_urgency(order.urgency),
            'localized_labour_intensity': get_localized_labour_intensity(order.labour_intensity),
        })
    return orders_list

def get_employee_orders(id):
    orders = Order.objects.filter(id_employee=id)
    orders_list = []
    for order in orders:
        orders_list.append({
            'order_object': order,
            'localized_status': get_localized_status(order.status),
            'localized_payment_status': get_localized_payment_status(order.payment_status),
            'localized_urgency': get_localized_urgency(order.urgency),
            'localized_labour_intensity': get_localized_labour_intensity(order.labour_intensity),
        })
    return orders_list

def get_order_materials(id_order):
    order_materials_object = OrderMaterials.objects.filter(id_order=id_order)

    materials_list = []
    for item in order_materials_object:
        quantity = item.material_quantity
        price = get_current_price(item.id_material.id)
        cost = quantity * price
        kek = {
            'material_object': Material.objects.get(id=item.id_material.id),
            'quantity': quantity,
            'price': price,
            'cost': cost 
        }
        materials_list.append(kek)
    
    return materials_list

def get_localized_status(status):
    order_statuses = {
        'Created': _('Created'),
        'Cancelled': _('Cancelled'),
        'In progress': _('In progress'),
        'Completed': _('Completed'),
        'Fitting required': _('Fitting required'),
        'Returned for rework': _('Returned for rework')
    }
    return order_statuses[status]
    
def get_localized_payment_status(payment_status):
    payment_statuses = {
        'Pending payment': _('Pending payment'),
        'Prepayment made': _('Prepayment made'),
        'Paid': _('Paid')
    }
    return payment_statuses[payment_status]

def get_localized_urgency(urgency):
    urgencies = {
        'Low': _('Low urgency'),
        'Medium': _('Medium urgency'),
        'High': _('High urgency'),
        'Very high': _('Very high urgency')
    }
    return urgencies[urgency]

def get_localized_labour_intensity(labour_intensity):
    labour_intensities = {
        'Low': _('1-3 days'),
        'Medium': _('4-6 days'),
        'High': _('7-9 days'),
        'Very high': _('10+ days')
    }
    return labour_intensities[labour_intensity]

@login_required(login_url='auth')
def add_order(request):
    context = {}
    context['user_group'] = request.user.groups.all()[0].name

    errors = ''
    if request.method == 'POST':
        order_form = OrderForm(request.POST)

        if order_form.is_valid():
            saved_form = order_form.save(commit=False)
            saved_form.start_date = datetime.now()
            saved_form.save()
            return redirect('all_orders')
        else:
            errors = order_form.errors

    order_form = OrderForm()
    context['form'] = order_form
    context['errors'] = errors

    return render(request, 'order/add_order.html', context)
    

templates/order/add_order.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}

{% block title %}{% trans "Add order" %}{% endblock %}

{% block content %}

<!-- For DateTimePicker (flatpickr) -->
<script src="https://npmcdn.com/flatpickr/dist/l10n/ru.js"></script>

{% block extra_css %}
{{ form.media.css }}
{% endblock %}

{% block extra_js %}
{{ form.media.js }}
{% endblock %}
<!--  -->

<a class="btn btn-link" href="{{request.META.HTTP_REFERER}}">← {% trans 'Previous page' %}</a>

<h1>{% trans "Add order" %}</h1>

{% if errors %}
<div class="alert alert-danger" role="alert">
    {{ errors }}
</div>
{% endif %}
<form class="mt-4" method="POST">
    {% csrf_token %}
    <div class="form-row mb-2 mt-2">
        {{ form.status }}
        <div class="col-md-4 mb-3">
            <label for="id_id_service">{% trans "Service" %}</label>
            {{ form.id_service }}
        </div>
        <div class="col-md-4 mb-3">
            <label for="id_id_client">{% trans "Client" %}</label>
            {{ form.id_client }}
        </div>
    </div>
    <div class="form-row mb-2">
        <div class="col-md-4 mb-3">
            <label for="id_target_completion_date">{% trans "Desired completion date" %}</label>
            {{ form.target_completion_date }}
        </div>
        <div class="col-md-4 mb-3">
            <label for="id_labour_intensity">{% trans "Labour intensity" %}</label>
            {{ form.labour_intensity }}
        </div>
        <div class="col-md-4 mb-3">
            <label for="id_urgency">{% trans "Urgency" %}</label>
            {{ form.urgency }}
        </div>
    </div>

    <h4>{% trans "Executor" %}</h4>
    <div class="form-row mb-2 mt-2">
        <div class="col-md-4 mb-3">
            <label for="id_id_employee">{% trans "Sewer" %}</label>
            {{ form.id_employee }}
        </div>
    </div>

    <h4>{% trans "Order materials" %}</h4>
    <div class="form-row mb-2">
        <div class="col-md-4 mb-3">
            <label for="id_id_category">{% trans "Order materials" %}</label>
            {{ form.id_category }}
        </div>
    </div>

    <h4>{% trans "Payment section" %}</h4>
    <div class="form-row mb-2 mt-2">
        <div class="col-md-4 mb-3">
            <label for="id_payment_status">{% trans "Payment status" %}</label>
            {{ form.payment_status }}
        </div>
        <div class="col-md-4 mb-3">
            <label for="id_prepayment">{% trans "Prepayment" %}</label>
            {{ form.prepayment }}
        </div>
        <div class="col-md-4 mb-3">
                <label for="id_cost">{% trans "Cost" %}</label>
                {{ form.cost }}
        </div>
    </div>
    <div class="form-row mb-3">
        
        <div class="col-md-12 mb-3">
            <label for="id_comment">{% trans "Comment" %}</label>
            {{ form.comment }}
        </div>
    </div>
    
    <button class="btn btn-success" type="submit" id="add_order_button">{% trans "Save" %}</button>
</form>

<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>
<script src="{% static 'js/Order/updateUrgency.js' %}"></script>

{% endblock %}

templates/order/all_orders.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans "Orders" %}{% endblock %}

{% block content %}

<h1>{% trans "Orders" %}</h1>
<div class="table-responsive mt-3">
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">{% trans "#" %}</th>
                <th scope="col">{% trans "Status" %}</th>
                <th scope="col">{% trans "Payment status" %}</th>
                <th scope="col">{% trans "Employee" %}</th>
                <th scope="col">{% trans "Client" %}</th>
                <th scope="col">{% trans "Service" %}</th>
                <th scope="col">{% trans "Start date" %}</th>
                <th scope="col">{% trans "Cost" %}</th>
            </tr>
        </thead>
        <tbody>
            {% for order in orders %}
                <tr>
                    <th scope="row">
                        <a href="{% url 'view_order' id=order.order_object.id %}">{{ order.order_object.id }}</a>
                    </th>
                    <td>{{ order.localized_status }}</td>
                    <td>{{ order.localized_payment_status }}</td>
                    <td>
                        {% if order.order_object.id_employee %}
                            <a href="{% url 'view_employee' id=order.order_object.id_employee.user.id %}">{{ order.order_object.id_employee }}</a>
                        {% else %}
                            <i>{% trans "Undefinedd" %}</i>
                        {% endif %}
                    </td>
                    <td>
                        {% if order.order_object.id_client %}
                            <a href="{% url 'view_client' id=order.order_object.id_client.id %}">{{ order.order_object.id_client }}</a>
                        {% else %}
                            <i>{% trans "Undefinedd" %}</i>
                        {% endif %}
                    </td>
                    <td>
                        {% if order.order_object.id_service %}
                            <a href="{% url 'view_service' id=order.order_object.id_service.id %}">{{ order.order_object.id_service }}</a>
                        {% else %}
                            <i>{% trans "Undefinedd" %}</i>
                        {% endif %}
                    </td>
                    <td>{{ order.order_object.start_date }}</td>
                    <td>{{ order.order_object.cost }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

templates/order/view_order.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans "Order" %} #{{ order.order_object.id }}{% endblock %}

{% block content %}
<a class="btn btn-link" href="{{request.META.HTTP_REFERER}}">← {% trans 'Previous pagee' %}</a>

<h1>{% trans "Order" %} #{{ order.order_object.id }}</h1>
<div class="table-responsive mt-3">
    <table class="table">
        <tbody>
            <tr>
                <th scope="row">{% trans "Servicee" %}</th>
                <td>
                    {% if order.order_object.id_service %}
                        <a href="{% url 'view_service' id=order.order_object.id_service.id %}">{{ order.order_object.id_service }}</a>
                    {% else %}
                        <i>{% trans "Undefinedd" %}</i>
                    {% endif %}
                </td>
            </tr>
            <tr>
                <th scope="row">{% trans "Statuss" %}</th>
                <td>{{ order.localized_status }}</td>
            </tr>
            <tr>
                <th scope="row">{% trans "Payment status" %}</th>
                <td>{{ order.localized_payment_status }}</td>
            </tr>
            <tr>
                <th scope="row">{% trans "Prepayment" %}</th>
                <td>{{ order.order_object.prepayment }}</td>
            </tr>
            <tr>
                <th scope="row">{% trans "Cost" %}</th>
                <td>{{ order.order_object.cost }}</td>
            </tr>
            <tr>   
                <th scope="row">{% trans "Start date" %}</th>
                <td>{{ order.order_object.start_date }}</td>
            </tr>
            <tr>
                <th scope="row">{% trans "Target completion date" %}</th>
                <td>{{ order.order_object.target_completion_date }}</td>
            </tr>
            <tr>
                <th scope="row">{% trans "End date" %}</th>
                <td>{{ order.order_object.end_date }}</td>
            </tr>
            <tr>
                <th scope="row">{% trans "Client" %}</th>
                <td>
                    <a href="{% url 'view_client' id=order.order_object.id_client.id %}">{{ order.order_object.id_client }}</a>
                </td>
            </tr>
            <tr>
                <th scope="row">{% trans "Employee" %}</th>
                <td>
                    <a href="{% url 'view_employee' id=order.order_object.id_employee.user.id %}">{{ order.order_object.id_employee }}</a>
                </td>
            </tr>
            <tr>
                <th scope="row">{% trans "Urgency" %}</th>
                <td>{{ order.localized_urgency }}</td>
            </tr>
            <tr>
                <th scope="row">{% trans "Labour intensity" %}</th>
                <td>{{ order.localized_labour_intensity }}</td>
            </tr>
            {% if order.order_object.comment %}
                <tr>
                    <th scope="row">{% trans "Comment" %}</th>
                    <td>{{ order.order_object.comment }}</td>
                </tr>
            {% endif %}
        </tbody>
    </table>
</div>

<h4>{% trans "Order materials" %}</h4>
<div class="table-responsive mt-3">
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">{% trans "Name" %}</th>
                <th scope="col">{% trans "Category" %}</th>
                <th scope="col">{% trans "Price" %}</th>
                <th scope="col">{% trans "Quantity (meters or pieces)" %}</th>
                <th scope="col">{% trans "Cost" %}</th>
            </tr>
        </thead>
        <tbody>
            {% if order.materials %}
                {% for material in order.materials %}
                    <tr>
                        <td>
                            <a href="{% url 'view_material' id=material.material_object.id %}">{{ material.material_object.name }}</a>
                        </td>
                        <td>
                            <a href="{% url 'view_category' id=material.material_object.id_category.id %}">{{ material.material_object.id_category }}</a>
                        </td>
                        <td>{{ material.price }}</td>
                        <td>{{ material.quantity }}</td>
                        <td>{{ material.cost }}</td>
                    </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td colspan="5" class="text-center font-italic">{% trans "There are not any order materials" %}</td>
                </tr> 
            {% endif %}
        </tbody>
    </table>
</div>

<h4>{% trans "Fittings" %}</h4>
<div class="table-responsive mt-3">
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">{% trans "Index number" %}</th>
                <th scope="col">{% trans "Date" %}</th>
                <th scope="col">{% trans "Statuss" %}</th>
            </tr>
        </thead>
        <tbody>
            {% if order.fittings %}
                {% for fitting in order.fittings %}
                    <tr>
                        <td>{{ fitting.fitting_object.index_number }}</td>
                        <td>{{ fitting.fitting_object.date }}</td>
                        <td>{{ fitting.localized_fitting_status }}</td>
                    </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td colspan="3" class="text-center font-italic">{% trans "There was not any fittings" %}</td>
                </tr> 
            {% endif %}
        </tbody>
    </table>
</div>

{% endblock %}